apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- data-folder.yaml
- grf-files.yaml
- rochargen-deployment.yaml
- rochargen-service.yaml

images:
- name: rochargen
  newName: registry.digitalocean.com/titanro-docr/rochargen@sha256:2108519258b0e7eecf9b82a7f7519ec01be2579818302b5de977b722d615dda3
